DROP TABLE IF EXISTS carts CASCADE;

CREATE TABLE carts(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);